// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BusUrl():Promise<string>;

export function Emit(arg1:string,arg2:string):Promise<void>;

export function Online():Promise<boolean>;

export function Send(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;
