// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BusUrl() {
  return window['go']['main']['Bridge']['BusUrl']();
}

export function Emit(arg1, arg2) {
  return window['go']['main']['Bridge']['Emit'](arg1, arg2);
}

export function Online() {
  return window['go']['main']['Bridge']['Online']();
}

export function Send(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Bridge']['Send'](arg1, arg2, arg3, arg4);
}
